apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: democratic-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.15.0
  name: democratic-csi-node-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: democratic-csi-node-cr
subjects:
  - kind: ServiceAccount
    name: democratic-csi-node-sa
    namespace: democratic-csi
