apiVersion: v1
data:
  extra-ca-certs: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: democratic-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.15.0
  name: democratic-csi
  namespace: democratic-csi
