apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller-linux
    app.kubernetes.io/csi-role: controller
    app.kubernetes.io/instance: democratic-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.15.0
  name: democratic-csi-controller
  namespace: democratic-csi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-linux
      app.kubernetes.io/csi-role: controller
      app.kubernetes.io/instance: democratic-csi
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: democratic-csi
  template:
    metadata:
      annotations:
        checksum/configmap: be3be23b8b52f8a7bc9319f0e70f83561f80a3ac2567bde5ff721188dc747e6a
      labels:
        app.kubernetes.io/component: controller-linux
        app.kubernetes.io/csi-role: controller
        app.kubernetes.io/instance: democratic-csi
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: democratic-csi
    spec:
      containers:
        - args:
            - --v=5
            - --leader-election
            - --leader-election-namespace=democratic-csi
            - --timeout=90s
            - --worker-threads=10
            - --csi-address=/csi-data/csi.sock
          image: registry.k8s.io/sig-storage/csi-attacher:v4.4.0
          name: external-attacher
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
        - args:
            - --v=5
            - --leader-election
            - --leader-election-namespace=democratic-csi
            - --timeout=90s
            - --worker-threads=10
            - --extra-create-metadata
            - --csi-address=/csi-data/csi.sock
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
          name: external-provisioner
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
        - args:
            - --v=5
            - --leader-election
            - --leader-election-namespace=democratic-csi
            - --timeout=90s
            - --workers=10
            - --csi-address=/csi-data/csi.sock
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          image: registry.k8s.io/sig-storage/csi-resizer:v1.9.0
          name: external-resizer
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
        - args:
            - --csi-version=1.5.0
            - --csi-name=org.democratic-csi.iscsi
            - --driver-config-file=/config/driver-config-file.yaml
            - --log-level=info
            - --csi-mode=controller
            - --server-socket=/csi-data/csi.sock.internal
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: /tmp/certs/extra-ca-certs.crt
          image: docker.io/democraticcsi/democratic-csi:latest
          livenessProbe:
            exec:
              command:
                - bin/liveness-probe
                - --csi-version=1.5.0
                - --csi-address=/csi-data/csi.sock.internal
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 15
          name: csi-driver
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
            - mountPath: /config
              name: config
            - mountPath: /tmp/certs
              name: extra-ca-certs
        - env:
            - name: BIND_TO
              value: unix:///csi-data/csi.sock
            - name: PROXY_TO
              value: unix:///csi-data/csi.sock.internal
          image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.6
          name: csi-proxy
          volumeMounts:
            - mountPath: /csi-data
              name: socket-dir
      dnsPolicy: ClusterFirst
      hostAliases: []
      hostIPC: false
      hostNetwork: false
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      serviceAccount: democratic-csi-controller-sa
      volumes:
        - emptyDir: {}
          name: socket-dir
        - name: config
          secret:
            secretName: democratic-csi-driver
        - configMap:
            items:
              - key: extra-ca-certs
                path: extra-ca-certs.crt
            name: democratic-csi
          name: extra-ca-certs
