apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: democratic-csi-driver
  namespace: democratic-csi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHdlMHp3MW93c014QUV1
        UUxlTTUvelF5VlA4TC9FRlRYRWlFUkdZTUdJCmRheUZZZzNLZWs0NHZlbTNGcGU1
        YVFtcENZUEZDVTB3d2FpbllaWXorQm8KLS0tIE82c0hsZ0R4TDVVRnMvUSszQzk5
        a0tOUk5TdjRhRmtBQ0dCRnRIYVk2Sm8KSMBQIqYgoFkG1WQJGZ2/o3GnKY6g4QS0
        y0JYmlnQoECJn830jfTaZUT0NV6av5P2Gx6R7jEDnunPDQK79Xew+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjhzUkd5VVZxUXRyeFky
        NEM5NUJXYXJNQkRoSHJwMkw4aGk3MGtBZ0FrCmVYYi9vRndFN2R3ZkUrMzdJaWVm
        Wjd4dDd1eFdRMzdCZS83ajF5Y1JoV2sKLS0tIHIwNnpFbnhGRHJXN1hKT2lxOE9I
        czhtbFVJSDFRSzd5emRBc1dyY0k2eFkKUrKcQk2ObJqIem19q9DgtRcmXO6PLbSv
        7ixx9QqS2dqKVnd/o0QE2GvxmQXxujFwar/2HsTrH6ECpS1NU5Bp8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-20T14:36:39Z"
  mac: ENC[AES256_GCM,data:fh4iW5LE88DOhKVA+pEqNQ13jRW+zW6xxqCHfb6yf/43PSaV6L1WzIwIsmvQQH/7WNl2IARGMSa3Nhs6pLkQs8DEtKv11GmDSPdJCMqOEW6fMsaIvpdDlbvlv9zaMHQvYM85cw+AvUhAfJDGDmhbYsGQaHpUpHnxgb94nUHLOPQ=,iv:+5GGKTS+DWnR1+LklPDQggNqkDchStfK9VGhYfza/jM=,tag:4mbeD6H0RypzEdkOe0PiUg==,type:str]
  version: 3.10.2
spec:
  secretTemplates:
    - name: democratic-csi-driver
      stringData:
        driver-config-file.yaml: ENC[AES256_GCM,data:YxaG8JScq/fMdlaLTgIfwIe1ss4N8TQsn5t0InbFNpcX8oMGrovEhmJkaYFZwOWvREZNc6mR6ZD/msnmd21vH2QDLR5Ag6zWY72gaLfEpJ0HJcv03Dj5TwV7yC8AuexL6Z95VQ74867cyiIWYIldgZnwrR+xJROqb2xboxJST3VVAqPEpx9ZylRtv9zkHGrB/jBfte7NMxEf2Qe6NjlZRZajQoFW7QfHUnRgQomjKISwHyq53aB3wT3FMpnaFMV4B7ldTH+nCl1mAxUY9rsyGrUajOjLhGmPgoRxFcg5TLaBxoyIg3QMzpbcDjnsM8kyO2wjXvYhiJrPdTwQ6zaGkgb3iuAzD9+LwQgFz1rvChTf7VGHjYvOFuP71SUCaySEStY7HAKT1gudNziuV4aHqbIkKbQI9VP+JZibeQO8VYOTYK93rnJdvGbb3Rcar7uHxEwxSFr2OKYdvJAMKFv3MIYM8scHffyEg2zlAhtn8VxvoRD1LJ4Lwff6RDkBMKN+B05FI2LIokKQzRIzaXRbZcKUMtGe3nm+qNVk1A2ohCXNR2/jLPCcAs9XuvPRBcj5Ygujl38ya/eAD2LC171DuhqDpx4aBb+zOtz0YRma8aYoqxGymc58p0iRv85bNKx0lArO1yAAE4SGhG7RdZuwhTQIXWN/XZ5MMbcNT6Oa+1t4gXCeQSh7udJfcKrplcZNGQPgX+nWHgKfaaieD0W+q0maI+qEtBftByXwW71o12I3MapyMG9YlRj10iTEoO6OvJ73Z9PX3jDT/38GBLIMlBQl1WC8zylUHX8iTH0ZIHE/hxgnzL1AjxAHRt3uHAdSIIeRbSO+MHyq5cxxxHb/QD+IoBHqdIwzGE4PFkW9COdW+4SSFQRanHkQ2VuiEDps2eBXww8OWGlkYFXdLSaQbr2ATPHzYjSEX0wC3igQ85XoG2GX9R2yqT5V3q7QfbMP7mqwShjxe+8xklx9nLppqQBJ8R/g46358eQ3aOujajkgVvGjbwskNTa9BLTtU4fHjhf8Dgf5CQBj+VNu9autXGHXd6ofFWN+AsTTE/Kw0vlpkk9sYCrrm+e1nYtE71RqINtdS/FTgYuyoFQ9hdcw4BtwjSzWoHCQY2g8MxeyoDucPprjm90XJnue8Fy3Q6K9DoFnrtK8HCxtsDCi+KyasWIAJHKMmEe+yyk3VYWuBdnmjfC8XOmZvpUPdwQI6e+YXffRoPsp6vc65ugkY0dl6Mel/0I40oqV2GTFjRpBjvzlS5MDdGv8xRGRqDA6DpqIbYYHmLuv3hLiKnFVhlZ0VuYSOZ83X/LKtANag2IHG4+7DZ2vHznAj7LNHwd6yUj2irEB9gu4XzHJwZpdtbAwdYQDSwon6uNNcm9c5ZzY7UN+/+xu48JChJIEzShcn/sEEEOhAHcZGTHCqlsWPWIP8GEL41kNwiSwUFJv5+Hf194gEFFhC9hw6lsMxwkIuICAn29E4gAulhhGHGjmat2IvCJd6xsB6kWU6ZSt/9kkt7+kAplpAShMlFiTAetphdnheCMsrJv2XivOxeAPy4tMtYAdqKDcasybadPTCloougevK1sVyfUZyJUSOaG7kv+axIWdpXVUYcTKLshA160yTITAzbtymPkRHOl+UCeT8tzlbS3iqOO1/NaztCCbHVlVzlPrCBqcY7ySXxy13WIHmkZ7xQCjNa4y7fzAme7Q,iv:KkcH3UNddCUeYxYhA5Z64XMtFPZ7Mj047pV5VgA7aOY=,tag:jutCIyHIgLQsPPDJzA9Wsw==,type:str]
  suspend: false
