apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: democratic-csi-driver
  namespace: democratic-csi
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHdlMHp3MW93c014QUV1
        UUxlTTUvelF5VlA4TC9FRlRYRWlFUkdZTUdJCmRheUZZZzNLZWs0NHZlbTNGcGU1
        YVFtcENZUEZDVTB3d2FpbllaWXorQm8KLS0tIE82c0hsZ0R4TDVVRnMvUSszQzk5
        a0tOUk5TdjRhRmtBQ0dCRnRIYVk2Sm8KSMBQIqYgoFkG1WQJGZ2/o3GnKY6g4QS0
        y0JYmlnQoECJn830jfTaZUT0NV6av5P2Gx6R7jEDnunPDQK79Xew+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjhzUkd5VVZxUXRyeFky
        NEM5NUJXYXJNQkRoSHJwMkw4aGk3MGtBZ0FrCmVYYi9vRndFN2R3ZkUrMzdJaWVm
        Wjd4dDd1eFdRMzdCZS83ajF5Y1JoV2sKLS0tIHIwNnpFbnhGRHJXN1hKT2lxOE9I
        czhtbFVJSDFRSzd5emRBc1dyY0k2eFkKUrKcQk2ObJqIem19q9DgtRcmXO6PLbSv
        7ixx9QqS2dqKVnd/o0QE2GvxmQXxujFwar/2HsTrH6ECpS1NU5Bp8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-19T20:59:16Z"
  mac: ENC[AES256_GCM,data:fA/XW9LH2qe6fjRkP+aIm11HEVtO9axvUVJwN51iOCKsiEobP4tTgf8mQj4oKFZMYNOUMNOKwPjOeuh/W8NCkgLm1z9KqgWQoUQWwAORj5nheLmUkCWPA4HBzpRhLhd6tbNMCSQcDAADF2vd33rSC+sudggjp0SKCV8moWVjGGI=,iv:yidOVzgMKOwIjXh0ceAqWPeWBE+vwDkGFBgj759pZNQ=,tag:UeFDMofCmmR/tF8m9qp+Lg==,type:str]
  version: 3.10.2
spec:
  secretTemplates:
    - name: democratic-csi-driver
      stringData:
        driver-config-file.yaml: ENC[AES256_GCM,data:fEE3MbzD3SdQuPcsxUR2sh9MCZt+MhvL1bY4J0zW1dQQNvpzosYZkt9Mq9r6OIuRB6Pkt//e5wRd1EwHaihkoWdM0/+TjjTQJGaZHcIvdFQD5qhsAqRDI917HChMdmkFKNn8qMRS9pqj0znObLmlzXsF/ktgKCGtV4PeLFv7YOSqwgy9IpPhWCFDuUcWMmt+mTgikP8Lljd2VQnoz05InHNcogM5ES57hza9hT2D0hoIuG5VGf2buZ+drvPMMZPeE5qcs9lFs9khaZZ52KnXah1xkuSelPnBLT+p6Uz5+vl0AelDDE5qOJyJYeLK0V/UBg740Db74xs/ERxuNwbkbRDwTFxbcSEViCUPXD+NbF7/sRV+2mjKPaaa29spNDOCH68VUOudotEvd8XqPRZZzIAdjVOE05wU/lHwgut6h5ZGQpkFjjUvVomwCn++xveLoNMUioC/Viae43IWKNMs573EfBK3WLWE71r7lXNB7x7jMGLbzOA5jLhCjiEOk7MN8Td5+dzUiKiedXfaa7MA7Jtu2U9V8lN5hLNI7WO3cWC8ljHOy6QyXwzg5NGAsqG49NxYBsI5+TkyJMMEODZmRrnBPCq+x4W5RL/ePCRf7UgnM7zxeR2pPy6LrPk4NaURRlk5WQHQnmna7RKUvRIB65jv/TpQzKYDL9ueLkOVsuWKTOggd9KeNKESudMf7y+bp1SvTUwJRfahdInjCkeyHhKt702lKa9jyPQWWTeIKnuUOtAHQ/HIw5heTY58GEUSHRyRiUbVqtJ6drsdhTZLrKwdMoz0V2T3AEMQF2sfa7D1ChrYI1xO8JhbRDaQ1NXWVPZ7VHW19aVmhON+RAgI2u1cPvG5zA/lWKb2VHsT4zLeig7BjkKoPAAcb3i7n9MthcOHhX9wuRBiotBsKz8XQycHTS23Pg+xH6Eyw+64bCNjikBxF0jg2R++xLLtU3y9RyHnSlNkBQRcmQ31WcQIAIHJtaAzNTQ3jO1TVZeez54WzeIyiMJiLAcy1fR/tEfPArAKireji5KfNhT4PJd+Wd4YtQ0bYKKryy7xO0m7psEM3sRHx6Rk7DInC7Xt/2gUgR3Aq9X9YErUyFbRb7xyO2tENksSTJOHOV1roggPd93LK5bs14Td12ZdHusZCb7lQVK0qMIkw1a+Ac5YQGUgfsrXUHPwknX8Ae5zEytZteyAG5M/MPhpfibTzphSfG9SD9cug4bQNmftzND+b8Pr40clmK+UsaAsrC1zbtmYqijT+Fw38+oKZqHnOfmgxdMpXEagJpaza4rAEcMM2RoN68IQY6MrcMyWK13Bx17QmhXSRWJSqkG9av7YFwl8CnwBGQDuX8WZoKHCwDUOrCO1a3GxUR0RR1hKmvgX9HlvdkXwK0COmoMcYMZN3XTE5v6FEqm3F1N1m2F7ikCAtFunWquCzP0ECtxbV7W9IEuS2I9sG3ItMz+nBFWiXlo6UrqDURegtR1zXTqYb/F7Z5QJeuvjtVuAIkBseUiMfmw02zTfZHDjpp9gQ8uZUviX6vAbEAFGBogt+5Q4Y7XuAOMK1nAHUEtsMS/SI3uxokugUqZQ7cRieW/K/48397K9BOagEiZ0m/nV97m61Xk1nnHroDbuZ6Ad5kjuKfbBjT29RHqU1NYupG97cgrWEXq2dJ68GGimam2puDGuSMAHXZ36nHZltevhNbCYgnIH3x3toqgyrTG1xaPsUzT9/POFpCmqdZ0G35fzWzsPjWdfow2YeaV7Ins853SRuJPE+Kr65N3tizc=,iv:TyYzi5WCvCqQQ5SgeejMOOiPl2Kb5rD8zKehzsJyW/I=,tag:r8s4o2MR8q60wUcqwnTa4g==,type:str]
  suspend: false
