apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluto-for-channels
  namespace: nodecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pluto-for-channels
  template:
    metadata:
      labels:
        app: pluto-for-channels
    spec:
      containers:
        - name: pluto-for-channels
          image: jonmaddox/pluto-for-channels:2.0.2
          envFrom:
            - secretRef:
                name: pluto-credentials
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
