apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pluto-secrets
spec:
    suspend: false
    secretTemplates:
        - name: pluto-credentials
          stringData:
            PLUTO_USERNAME: ENC[AES256_GCM,data:4kHzKKCwk7kfBz+y72qZ2Gk=,iv:Q44iKXT7Dku3Km9fBEr/CY5Rc9VWkijwDPCu2mn8G28=,tag:6Ikw/ALl6MbUhCGVQLAYkw==,type:str]
            PLUTO_PASSWORD: ENC[AES256_GCM,data:q/dkufo8Gf5VEtG6kGDfvH3s40Q=,iv:APjgALCJ+End92aVoClyxlVo664bnRXuRGZPEy0qdlU=,tag:jj8yP5dH3InHy2lYDQYGVA==,type:str]
sops:
    age:
        - recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TTdsZFJJK1lFK2RGU0Nq
            RkxvRE9pSWVKZW9oMGVzbzc3d2xWcDJUUWhrClEwd0VMN0o0eGJ3eUFxbmRFUVNp
            TVJiUERHZTJ0c1ZwaVo5dEpvSm40c3MKLS0tIDIvaFJRYXJGdU5xTkdQNzVEbHRv
            S24wTXBQZFhSWVlxTk5aNGRGKzhvQ1kK0PxJmlP4WxQiYRSVPGg6CDEWLTjTIByj
            J5GoizgCEuL+IavhfjyxGbI1Xh8QfZJWP6HTbob/B0kM8TeJWpezIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbFlWblUwczRkS09SZU5p
            UEc0VGw0V3NyRzNsTkhNMC9nSytuRzBQekRjCjVYUWE3OVZYN1FLbUFUUHhOTm1h
            aXUxVHdCaGZqN0FrTHJ3ZWhmaVp6Y2cKLS0tIGw0Q1ZLbGVHQUJlWDFJa0psUHJj
            Vm9selBnaTBLMEdMbTM2Mm9TMy9NM1UKoYCLNxpnX37uDU+BYt8zI4tqCTlG7P9y
            KSZy5a7RX4jEFg8yEqFNmyLPeW8iJwuv8vCUE69Y/cyDZm25oOXUXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T13:01:37Z"
    mac: ENC[AES256_GCM,data:0H8Jfm9mxG+/b3Hu3/DDsXJzJivo5624xQxtS7OeumqiI2H7ghsjN92gtFuCo06ydrYnjTHmtltbEm6eV43XkUCU6Fe91NyoEPklt2vZRPjVHxg5Tbu+4htuOOg2p3syNovb2mNdON1g9+dBgFutmZRrXE2aYJbC867hkwJklBE=,iv:xjKSRJOr7DCWHnxP8sOyXq+2yOvOctXaOkE1yco54sU=,tag:yJA8iPOpx0YAL+7OKLPhNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
