apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 70.4.2
    chart: kube-prometheus-stack-70.4.2
    heritage: Helm
    jobLabel: kube-etcd
    release: kube-prometheus-stack
  name: kube-prometheus-stack-kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2381
      protocol: TCP
      targetPort: 2381
  selector:
    k8s-app: kube-controller-manager
  type: ClusterIP
