apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nodecast-secrets
spec:
    suspend: false
    secretTemplates:
        - name: nodecast-oidc
          stringData:
            OIDC_ISSUER_URL: ENC[AES256_GCM,data:0DroIYarpHEIC7AKzmjkQxTbt3Sbxa6bJmwRm5iWnpMZbtCQwTxk1TTU8XRqG/haxA==,iv:TX7u7e4rquqKX1mYbEA8aPgDxWvP4dfbiLJyBj9rA5Q=,tag:nSYjGvQ95jGuz1iSRVWOwA==,type:str]
            OIDC_CLIENT_ID: ENC[AES256_GCM,data:Z8YLY3yMWum9UbDkopHrusbUi4alVTcKx6vPo+2SuVNC38urxx3RNQ==,iv:EJaR2GBb61WOfweB3Q7ZzkoYfmDXd5VRKOAPtzA7FpE=,tag:q/KX2BTMTAp/Xh2MtzpDvg==,type:str]
            OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UUARhBSpKyVoKXb2btTSZRNqfsveZ3esxJ0xMv2oOTdb+cXiEgHztkC7ohAC47oMKjrCrD8jXUhcvZokUp1QNKx3xb9WkKve7CGwdSrj8r77+JlgV1INFZ1uGpAddu2/sTDREVAzNcISDI/zW4aZVanloxbSbOG01A9VvCwq0aM=,iv:H9k/E2ckdODP7feA/Gmdx6tZ/BmNMTcdHS4aehlpWMk=,tag:CiljfqDeGAow/6PHJSpbiA==,type:str]
            OIDC_AUTH_URL: ENC[AES256_GCM,data:9QZ9BsEY/IWmR5oIr+X9Dah/jPfS8NyRF0rZsT9NA7Uij9U0pdnCFK2tY/dMqOY=,iv:EJ0sWYsgjGBUAWCp5NM8u/47kidz+Vkldo30NIDrsYk=,tag:G1yIzenooLQ0fh6PhdsvGw==,type:str]
            OIDC_TOKEN_URL: ENC[AES256_GCM,data:Enyrv4jBXSgWvdlSOIbKexoj1HyK60MMk0LX3/sbedumkHOqVFe3b3SB+g==,iv:i5gCbD7Tdel1LVHaP4KomcWRRGU3X6rmYFi9mtDGBhI=,tag:/0uOxQLPT9elTcylFcvTAw==,type:str]
            OIDC_USERINFO_URL: ENC[AES256_GCM,data:+JHuYn5CAbKLeES8v9nFBfguve2krSKzR5tnG91RJUb4xXeSHoXeWKPL1LMa8w==,iv:5wdk6NXaKObY77Ub2dVlv6uKJHwlaBrhl1t3u6vufps=,tag:RE2CubRi3DCo7x53vMiG7A==,type:str]
            OIDC_CALLBACK_URL: ENC[AES256_GCM,data:hT1mqZDpbHwBk8YkLD0BXm/BvFzf78tJmmUtpMIfuP+gv6ER9SlOVsf4shaP+gFMx8ETNfFc4zAYGDjW7wm2,iv:hu4oG+3XgBtYlk3kUtmHPEROuZd1tZehCxi5x+2JyHg=,tag:a6yQ2pB2ygwlmHuSBFMZpg==,type:str]
sops:
    age:
        - recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHdlMHp3MW93c014QUV1
            UUxlTTUvelF5VlA4TC9FRlRYRWlFUkdZTUdJCmRheUZZZzNLZWs0NHZlbTNGcGU1
            YVFtcENZUEZDVTB3d2FpbllaWXorQm8KLS0tIE82c0hsZ0R4TDVVRnMvUSszQzk5
            a0tOUk5TdjRhRmtBQ0dCRnRIYVk2Sm8KSMBQIqYgoFkG1WQJGZ2/o3GnKY6g4QS0
            y0JYmlnQoECJn830jfTaZUT0NV6av5P2Gx6R7jEDnunPDQK79Xew+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjhzUkd5VVZxUXRyeFky
            NEM5NUJXYXJNQkRoSHJwMkw4aGk3MGtBZ0FrCmVYYi9vRndFN2R3ZkUrMzdJaWVm
            Wjd4dDd1eFdRMzdCZS83ajF5Y1JoV2sKLS0tIHIwNnpFbnhGRHJXN1hKT2lxOE9I
            czhtbFVJSDFRSzd5emRBc1dyY0k2eFkKUrKcQk2ObJqIem19q9DgtRcmXO6PLbSv
            7ixx9QqS2dqKVnd/o0QE2GvxmQXxujFwar/2HsTrH6ECpS1NU5Bp8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T19:46:27Z"
    mac: ENC[AES256_GCM,data:A1zCI9RMsGPz7Ls3aXejAbla7qXnOoXgx/MwJeXs4p4r8sv4MWRsEz6gTg4gFKBQjhDMrdsDt5jQZto9wW14VMybgW4nw48NS+V5ZhVuMVm5WgQ7jVtHAekqt7WRm1HLExhx0wk9+DJ3E3j0msxfbCNwYxd6Ja7olL3gtu1g3Wo=,iv:H30t2L8+3x/RcVrYR+SxbyyzkFqzC9OUY/uV+ByxrAo=,tag:VK3dYWQGCnggFJ9114TyiA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
