apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/prod/kube-prometheus-stack
    repoURL: https://github.com/devusb/argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
