apiVersion: v1
data:
  passinit.sql: |
    ALTER USER root@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD("PLACEHOLDERROOTPASSWORD");
    ALTER USER romm@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD("PLACEHOLDERPASSWORD");
    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  labels:
    app: mariadb-15.9.0
    app.kubernetes.io/instance: romm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.7.2
    helm-revision: "1"
    helm.sh/chart: mariadb-15.9.0
    release: romm
  name: romm-mariadb-passinit
  namespace: romm
