apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: romm-10.23.0
    app.kubernetes.io/instance: romm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: romm
    app.kubernetes.io/version: 3.9.0
    helm-revision: "1"
    helm.sh/chart: romm-10.23.0
    release: romm
  name: romm-config
  namespace: romm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
