apiVersion: v1
kind: Secret
metadata:
  labels:
    app: romm-16.1.2
    app.kubernetes.io/instance: romm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: romm
    app.kubernetes.io/version: 4.8.0
    helm-revision: "1"
    helm.sh/chart: romm-16.1.2
    release: romm
  name: romm-romm-secrets
  namespace: romm
stringData:
  ROMM_AUTH_SECRET_KEY: jjuPfcbfjI5dODtvVs5euoQLh3I2y4jrX7VZrB1CtNdlf4YwG4aBpO1pkGZyom7m
type: Opaque
