apiVersion: v1
kind: Secret
metadata:
  labels:
    app: romm-10.23.0
    app.kubernetes.io/instance: romm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: romm
    app.kubernetes.io/version: 3.9.0
    helm-revision: "1"
    helm.sh/chart: romm-10.23.0
    release: romm
  name: romm-mariadbcreds
  namespace: romm
stringData:
  jdbc: jdbc:sqlserver://romm-mariadb:3306/romm
  jdbc-mariadb: jdbc:mariadb://romm-mariadb:3306/romm
  jdbc-mysql: jdbc:mysql://romm-mariadb:3306/romm
  mariadb-password: PLACEHOLDERPASSWORD
  mariadb-root-password: PLACEHOLDERROOTPASSWORD
  plainhost: romm-mariadb
  plainporthost: romm-mariadb:3306
  url: sql://romm:PLACEHOLDERPASSWORD@romm-mariadb:3306/romm
  urlnossl: sql://romm:PLACEHOLDERPASSWORD@romm-mariadb:3306/romm?sslmode=disable
type: Opaque
