apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: romm-secrets
  namespace: romm
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eHdlMHp3MW93c014QUV1
        UUxlTTUvelF5VlA4TC9FRlRYRWlFUkdZTUdJCmRheUZZZzNLZWs0NHZlbTNGcGU1
        YVFtcENZUEZDVTB3d2FpbllaWXorQm8KLS0tIE82c0hsZ0R4TDVVRnMvUSszQzk5
        a0tOUk5TdjRhRmtBQ0dCRnRIYVk2Sm8KSMBQIqYgoFkG1WQJGZ2/o3GnKY6g4QS0
        y0JYmlnQoECJn830jfTaZUT0NV6av5P2Gx6R7jEDnunPDQK79Xew+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1m97ls72xcy8v492xrru4keyjve0jcqytqne6jk62zl72j3xsqgrql0ckw2
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjhzUkd5VVZxUXRyeFky
        NEM5NUJXYXJNQkRoSHJwMkw4aGk3MGtBZ0FrCmVYYi9vRndFN2R3ZkUrMzdJaWVm
        Wjd4dDd1eFdRMzdCZS83ajF5Y1JoV2sKLS0tIHIwNnpFbnhGRHJXN1hKT2lxOE9I
        czhtbFVJSDFRSzd5emRBc1dyY0k2eFkKUrKcQk2ObJqIem19q9DgtRcmXO6PLbSv
        7ixx9QqS2dqKVnd/o0QE2GvxmQXxujFwar/2HsTrH6ECpS1NU5Bp8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcn2u0r03z48ytvn9tts9pkllyj9qx7zl4w0yn6uscghv3f5y9jqmvyy69
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2025-04-20T20:55:10Z"
  mac: ENC[AES256_GCM,data:k6ujDHzaaxHs6jtjo9jHuGJRELYML3ku6mmBWlNFliO2uvosgAx69tvGTkNYw9kJxH7WwDD0Prs75SnouvDqa2WaEIB3W/KfMBHgEAM7criYa5CYvw/FXu/D4m7LRNwyaYrpyDReWAnHEDkt1o2QFSVxCSJkK6hLIZvPxqvwezs=,iv:kdff9YXKaqrP/Av5Mw1QqHiZ8zB8DaeykSH94MdLfNk=,tag:Mn+nCRRLbe170lh2T35LpQ==,type:str]
  version: 3.10.2
spec:
  secretTemplates:
    - name: romm-secrets
      stringData:
        IGDB_CLIENT_ID: ENC[AES256_GCM,data:SAMCavxlt2RunKxkJnXydPH9fOxXvZkfxMw/AzQa,iv:BxRLlCWhohIB/zIuZGenIbsxsmLoBqq+QDAWxATlNh0=,tag:GT/anJwlRA3Kt3vtc7a61g==,type:str]
        IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:S0trPNdXWxgQVcoiC2BjUMuSR0ROJQ8SjtLmsiuk,iv:gc57cr1+1XfnK741XakoHd6dWybEEky81QY6JLQ48AA=,tag:7xJ4onMRnPzfRiteyEa4pw==,type:str]
        ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:RMIofo3f8JBieye8kNiysTvbAPrZt3ka3DxnpS5BPiMD19YDsZPqfbIwBPNSvmCqi/m1yI4iW8aGl6ibrMyeGw==,iv:oCq1uL0iPUaAxZ9ZIWZ4NZlKO5UoEHpkQcwBmQZ0Yes=,tag:pZxRFmT4vB+HV4/0pi0IWw==,type:str]
  suspend: false
